google_analytics: ['UA-82655257-2', 'robots-txt.readthedocs.io']
repo_url: https://github.com/bisarca/robots-txt
site_description: 'Bisarca robots.txt Management'
site_favicon: favicon.ico
site_name: 'bisarca/robots-txt'
